# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' geo_sum_c
#'
#' The geometric sum d+d^2 + .. d^term
#'
#' @param d First term
#' @param term number of terms
#' @return the sum d+d^2 + .. d^term
geo_sum_c <- function(d, term) {
    .Call(`_pvmicrosimr_geo_sum_c`, d, term)
}

#' hello 2 x world
#'
#' @param params_vec First term
#' @return 2 standing charge
#' @export
test_c <- function(params_vec) {
    .Call(`_pvmicrosimr_test_c`, params_vec)
}

#' seai_grant_c
#'
#' seai grant for domestic solar installation (2022 structure)
#' fast c++ implementation
#'
#' @param params_vec scenario parameter vector
#' @param s solar capacity in kW
#' @param b battery capacity in kWh
#' @return grant amount in euros
#' @export
seai_grant_c <- function(params_vec, s, b) {
    .Call(`_pvmicrosimr_seai_grant_c`, params_vec, s, b)
}

#' amort
#'
#' amortisation or annuity payment for unit principal
#'
#' @param r decimal interest rate
#' @param term term of loan or investment
#'
#' @return real value
#' @export
amort_c <- function(r, term) {
    .Call(`_pvmicrosimr_amort_c`, r, term)
}

#' get_sys_util_c
#'
#' fast implementation of the financial utility of investment in a household solar PV system. This is defined as the fractional reduction in net present value of all associated cashflows(NPV_0-NPV)/NPV_0 where NPV_0 is the net present value
#' of expected future bills (including inflation expectations, discounted out to a term) and NPV is the net present value of all future cashflows
#' when a solar PV investment is made (amortisation, feedin tariff revenues, reduced electricity bills, tax). The financial model assumes a 2-component roof with incremental pv investments
#' d_solar1 and d_solar2 and incremental battery installation d_battery.
#' This function calculates the financial partial utility for initial adoption (old_solar1=0 and old_solar2=0) or for augmentation of an existing installation.
#' It is assumed that no grant is available for augmenting an existing system.
#'
#' @param params_vec vector of scenario parameters extracted from R params environment using "mget"
#' @param demand annual household electrical energy demand (kWh) (from smart meter dataset).
#' @param old_imports annual energy (kWh) imports with existing system (old_solar1, old_solar2, old_battery)
#' @param old_exports annual energy exports (kWh) with existing system (old_solar1, old_solar2, old_battery)
#' @param old_solar1 existing installed solar capacity on half roof1
#' @param old_solar2 existing installed solar capacity on half roof2
#' @param old_battery currently installed battery
#' @param new_imports annual energy (kWh) import with new (proposed) system (old_solar1 + d_solar1, old_solar2 + d_solar2, old_battery+d_battery)
#' @param new_exports annual energy exports (kWh) with new (proposed) system (old_solar1 + d_solar1, old_solar2 + d_solar2, old_battery+d_battery)
#' @param d_solar1 additional solar capacity on roof1
#' @param d_solar2 additional solar capacity on roof2
#' @param d_battery kWh battery size increment in steps of 2.5 kWh
#' @param include_grant True or False
#' @param customer "domestic" is only option at the moment
#'
#' @return unscaled financial partial utility
#' @export
get_sys_util_c <- function(params_vec, demand, old_imports, old_exports, old_solar1, old_solar2, old_battery, new_imports, new_exports, d_solar1, d_solar2, d_battery, include_grant = TRUE, customer = "domestic") {
    .Call(`_pvmicrosimr_get_sys_util_c`, params_vec, demand, old_imports, old_exports, old_solar1, old_solar2, old_battery, new_imports, new_exports, d_solar1, d_solar2, d_battery, include_grant, customer)
}

